.TH github_pki 1 "19 March 2020"
.SH NAME
github_pki \- 
.SH SYNOPSIS
\fBgithub_pki\fP [OPTIONS]
.SH DESCRIPTION

.SH OPTIONS
.SS Application Options
.TP
\fB\fB\-V\fR, \fB\-\-version\fR\fP
Display version.
.TP
\fB\fB\-t\fR, \fB\-\-token\fR <default: \fI$GITHUB_TOKEN\fR>\fP
GitHub token
.TP
\fB\fB\-o\fR, \fB\-\-org\fR <default: \fI$GITHUB_ORG\fR>\fP
GitHub organization to include.
.TP
\fB\fB\-T\fR, \fB\-\-teams\fR <default: \fI$GITHUB_TEAMS\fR>\fP
GitHub teams to include (comma separated).
.TP
\fB\fB\-u\fR, \fB\-\-users\fR <default: \fI$GITHUB_USERS\fR>\fP
GitHub users to include (comma separated).
.TP
\fB\fB\-a\fR, \fB\-\-authorized-keys\fR <default: \fI$AUTHORIZED_KEYS\fR>\fP
authorized_keys file.
.TP
\fB\fB\-s\fR, \fB\-\-ssl-dir\fR <default: \fI$SSL_DIR\fR>\fP
SSL directory to dump X509 keys to.
.TP
\fB\fB\-m\fR, \fB\-\-manpage\fR\fP
Output manpage.
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
